### PR TITLE
Add rack-session.rb file to make usage with bundler easier

### LINKED ISSUE #6: Needs rack-session.rb
Bundler will only automatically require `lib/rack-session.rb` based on the gem name. I think you need to add it which requires "rack/session".

```
gem "sidekiq", path: ".."
gem "concurrent-ruby"

# with Rack >= 3.0
gem "rackup"
gem "rack-session"
```

```
% bundle exec rackup simple.ru
bundler: failed to load command: rackup (/Users/mperham/.gem/ruby/3.1.2/bin/rackup)
/Users/mperham/src/sidekiq/bare/simple.ru:18:in `block in <main>': uninitialized constant Rack::Session (NameError)
Did you mean?  Rack::RACK_SESSION
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `eval'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:106:in `new_from_string'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:97:in `load_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rack-3.0.0.beta1/lib/rack/builder.rb:67:in `parse_file'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:260:in `app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:421:in `wrapped_app'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:323:in `block in start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:379:in `handle_profiling'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:322:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/lib/rackup/server.rb:179:in `start'
	from /Users/mperham/.gem/ruby/3.1.2/gems/rackup-0.2.1/bin/rackup:5:in `<top (required)>'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `load'
	from /Users/mperham/.gem/ruby/3.1.2/bin/rackup:25:in `<top (required)>'
```

### PR DESCRIPTION
**Pull request by jeremyevans**
Fixes #6

### CODE REVIEW

**Comment by ioquatix** [comment]
How does this make it easier? Is this some kind of autoload hook?

**Comment by dentarg** [comment]
Bundler can autorequire the name in the Gemfile

https://bundler.io/man/gemfile.5.html#REQUIRE-AS

**Comment by ioquatix** [comment]
According to the bundler team, this should be trying to load `rack/session.rb`. So, I'll investigate why that might not be working.

**Comment by ioquatix** [comment]
I confirmed that this is not needed.

**Pull request closed without merging**
